# Generated by Django 2.1.7 on 2019-05-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoteFiscalizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoFiscalizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('tipo', models.CharField(blank=True, choices=[('ENTRADA', 'ENTRADA'), ('SAÍDA', 'SAÍDA')], default='ENTRADA', max_length=20, null=True)),
                ('observacao', models.CharField(blank=True, max_length=40, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sip.LoteFiscalizacao')),
            ],
        ),
        migrations.CreateModel(
            name='Notificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('cpf', models.CharField(blank=True, max_length=18, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=50)),
                ('telefone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=4)),
                ('ano_processo', models.CharField(blank=True, choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], default='2019', max_length=4, null=True)),
                ('processo', models.CharField(max_length=20, unique=True)),
                ('notificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sip.Notificado')),
            ],
        ),
        migrations.AddField(
            model_name='movimentofiscalizacao',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sip.Processo'),
        ),
        migrations.AlterUniqueTogether(
            name='processo',
            unique_together={('numero_processo', 'ano_processo')},
        ),
    ]
