# Generated by Django 2.1.7 on 2019-04-17 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=4)),
                ('ano_processo', models.CharField(blank=True, choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], default='2019', max_length=4, null=True)),
                ('processo', models.CharField(max_length=4, unique=True)),
                ('Notificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sip.Notificado')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='processo',
            unique_together={('numero_processo', 'ano_processo')},
        ),
    ]
