# Generated by Django 2.1.7 on 2019-05-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentofiscalizacao',
            name='controle',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
    ]
