# Generated by Django 2.1.7 on 2019-05-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0002_movimentofiscalizacao_controle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentofiscalizacao',
            name='controle',
            field=models.CharField(default=None, error_messages={'unique': 'This email has already been registered.'}, max_length=40, unique=True),
        ),
    ]
