# Generated by Django 2.1.7 on 2019-04-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0002_auto_20190417_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='Notificado',
            new_name='notificado',
        ),
    ]
