# Generated by Django 2.1.7 on 2019-05-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0003_auto_20190502_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentofiscalizacao',
            name='controle',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
    ]
