# Generated by Django 2.1.7 on 2019-04-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0003_auto_20190417_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='processo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
