# Generated by Django 2.1.7 on 2019-05-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0004_auto_20190502_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentofiscalizacao',
            name='controle',
            field=models.CharField(default=None, error_messages={'UniqueValidator': 'This email has already been registered.'}, max_length=40, unique=True),
        ),
    ]
