# Generated by Django 2.1.7 on 2019-04-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0004_auto_20190417_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteFiscalizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
