# Generated by Django 2.1.7 on 2019-04-17 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0005_lotefiscalizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoFiscalizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('movimento', models.CharField(blank=True, choices=[('ENTRADA', 'ENTRADA'), ('SAÍDA', 'SAÍDA')], default='ENTRADA', max_length=4, null=True)),
                ('observacao', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sip.LoteFiscalizacao')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sip.Processo')),
            ],
        ),
    ]
