# Generated by Django 2.1.7 on 2019-05-16 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sip', '0005_auto_20190513_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentofiscalizacao',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processo',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentofiscalizacao',
            name='controle',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
    ]
