# Generated by Django 2.1.7 on 2019-06-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0006_auto_20190516_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='pdf',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
