# Generated by Django 2.1.7 on 2019-04-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0006_movimentofiscalizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentofiscalizacao',
            name='movimento',
            field=models.CharField(blank=True, choices=[('ENTRADA', 'ENTRADA'), ('SAÍDA', 'SAÍDA')], default='ENTRADA', max_length=20, null=True),
        ),
    ]
