# Generated by Django 2.1.7 on 2019-06-10 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sip', '0007_processo_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LISTA LOTE FISCALIZAÇÃO', 'LISTA LOTE FISCALIZAÇÃO')], default='LISTA LOTE FISCALIZAÇÃO', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='processo',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='lotefiscalizacao',
            name='descricao',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='loteFiscalizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sip.LoteFiscalizacao'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
