# Generated by Django 2.1.7 on 2019-06-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0008_auto_20190610_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatorio',
            old_name='loteFiscalizacao',
            new_name='lote',
        ),
    ]
