# Generated by Django 2.2.1 on 2020-10-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0009_auto_20190611_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=100, unique=True)),
                ('potencial_poluidor', models.CharField(choices=[('ALTA', 'ALTA'), ('MÉDIA', 'MÉDIA'), ('BAIXA', 'BAIXA')], default='ALTA', max_length=30)),
            ],
        ),
    ]
